version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: winmart_db
      POSTGRES_USER: winmart
      POSTGRES_PASSWORD: winmart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: